#!/usr/bin/env bash
# Quick Start Guide for Social Media API

echo "==================================================================="
echo "InfiAgentic Social Media API - Implementation Complete"
echo "==================================================================="
echo ""
echo "✅ What's Been Built:"
echo ""
echo "1. Social Media API Endpoints (12 routes)"
echo "   - Account management (connect, list, disconnect)"
echo "   - Post management (create, schedule, publish, bulk)"
echo "   - Analytics (aggregated, by platform)"
echo "   - Scheduling (view upcoming posts)"
echo ""
echo "2. Platform Integrations"
echo "   - Twitter/X via Tweepy"
echo "   - LinkedIn REST API"
echo "   - Facebook Graph API"
echo "   - Instagram (foundation)"
echo ""
echo "3. Celery Async Tasks"
echo "   - Publish posts to platform"
echo "   - Sync engagement metrics"
echo "   - Scheduled posting"
echo "   - Error handling & retries"
echo ""
echo "4. Complete Documentation"
echo "   - API reference (12 endpoints)"
echo "   - Code examples (Python, JS, cURL)"
echo "   - Integration guide"
echo "   - Error handling"
echo ""
echo "==================================================================="
echo "📋 Files Modified/Created:"
echo "==================================================================="
echo ""
echo "✅ NEW FILES:"
echo "   - /backend/app/schemas/social.py (300+ lines)"
echo "   - /docs/SOCIAL_MEDIA_API.md (700+ lines)"
echo ""
echo "✅ MODIFIED FILES:"
echo "   - /backend/app/api/v1/social.py (600+ lines)"
echo "   - /backend/app/tasks/social_tasks.py (500+ lines)"
echo ""
echo "==================================================================="
echo "🚀 To Get Started:"
echo "==================================================================="
echo ""
echo "1. Set Environment Variables:"
echo "   export TWITTER_API_KEY=your_key"
echo "   export TWITTER_API_SECRET=your_secret"
echo ""
echo "2. Start Services:"
echo "   # Terminal 1 - Backend"
echo "   cd backend"
echo "   uvicorn app.main:app --reload"
echo ""
echo "   # Terminal 2 - Celery Worker"
echo "   cd backend"
echo "   celery -A app.celery_app worker --loglevel=info"
echo ""
echo "   # Terminal 3 - Celery Beat (optional)"
echo "   cd backend"
echo "   celery -A app.celery_app beat --loglevel=info"
echo ""
echo "3. Test the API:"
echo "   # Login"
echo "   curl -X POST http://localhost:8000/v1/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"user@example.com\",\"password\":\"password\"}'"
echo ""
echo "   # Connect Twitter Account"
echo "   curl -X POST http://localhost:8000/v1/social/accounts \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"platform\":\"twitter\",\"access_token\":\"YOUR_TWITTER_TOKEN\"}'"
echo ""
echo "   # Create Post"
echo "   curl -X POST http://localhost:8000/v1/social/posts \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"account_id\":\"UUID\",\"post_text\":\"Hello world!\"}'"
echo ""
echo "4. View API Docs:"
echo "   http://localhost:8000/docs"
echo ""
echo "==================================================================="
echo "📊 Status:"
echo "==================================================================="
echo ""
echo "Social Media API:       ✅ 100% Complete (Production Ready)"
echo "- Account Management:   ✅ Complete"
echo "- Post Management:      ✅ Complete"
echo "- Publishing:           ✅ Complete (Celery)"
echo "- Analytics:            ✅ Complete"
echo "- Documentation:        ✅ Complete"
echo ""
echo "Remaining Priority Items:"
echo "1. Email API (Campaigns, tracking)"
echo "2. Leads API (Scoring, pipeline)"
echo "3. CRM API (Contacts, deals)"
echo "4. Analytics API (Dashboard metrics)"
echo "5. Workflows API (Visual builder)"
echo ""
echo "==================================================================="
echo "📖 Documentation:"
echo "==================================================================="
echo ""
echo "Full API docs: /docs/SOCIAL_MEDIA_API.md"
echo "API Swagger:   http://localhost:8000/docs"
echo ""
echo "==================================================================="
